"""
models.py - Typed data models for CampusAssistantEnv

Defines:
- ActionType  : Enum of all valid agent actions
- DifficultyLevel : Task difficulty enum
- CampusState : Full environment state (OpenEnv observation)
- CampusAction : Typed action wrapper
- TaskDefinition : Task metadata & grading spec
- StepResult : Result of a single environment step
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class ActionType(str, Enum):
    """All valid actions an agent can take inside CampusAssistantEnv."""

    SEARCH_NOTES = "search_notes"
    SUMMARIZE_NOTES = "summarize_notes"
    CREATE_STUDY_PLAN = "create_study_plan"
    GENERATE_REMINDER = "generate_reminder"
    CREATE_QUIZ = "create_quiz"
    CREATE_CHECKLIST = "create_checklist"
    FINISH_TASK = "finish_task"

    @classmethod
    def values(cls) -> List[str]:
        return [e.value for e in cls]


class DifficultyLevel(str, Enum):
    """Task difficulty levels."""

    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------

@dataclass
class CampusState:
    """
    Full observable state returned by state() / reset() / step().

    This is the OpenEnv observation — a structured JSON-serialisable object.
    """

    # What the user wants to accomplish
    user_goal: str = ""

    # Human-readable task name
    task_name: str = ""

    # Steps still needed to complete the task (from the task spec)
    tasks_remaining: List[str] = field(default_factory=list)

    # Steps the agent has already completed
    completed_steps: List[str] = field(default_factory=list)

    # Which action types the agent has called so far
    tools_used: List[str] = field(default_factory=list)

    # Seconds remaining before the episode times out
    time_remaining: int = 300

    # Difficulty of the current task
    difficulty_level: DifficultyLevel = DifficultyLevel.EASY

    # Cumulative reward so far (0.0 – 1.0)
    current_reward: float = 0.0

    # Whether the episode has ended
    done: bool = False

    # Informational message from the last step
    last_message: str = ""

    # Content generated by tools (e.g. note summaries, quiz text)
    generated_content: Dict[str, str] = field(default_factory=dict)

    # Internal episode start epoch (not part of public observation)
    _episode_start: float = field(default_factory=time.time, repr=False)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain dict (JSON-serialisable) for the OpenEnv state()."""
        return {
            "user_goal": self.user_goal,
            "task_name": self.task_name,
            "tasks_remaining": self.tasks_remaining,
            "completed_steps": self.completed_steps,
            "tools_used": self.tools_used,
            "time_remaining": self.time_remaining,
            "difficulty_level": self.difficulty_level.value,
            "current_reward": round(self.current_reward, 4),
            "done": self.done,
            "last_message": self.last_message,
            "generated_content": self.generated_content,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CampusState":
        """Reconstruct a CampusState from a plain dict."""
        s = cls()
        s.user_goal = data.get("user_goal", "")
        s.task_name = data.get("task_name", "")
        s.tasks_remaining = data.get("tasks_remaining", [])
        s.completed_steps = data.get("completed_steps", [])
        s.tools_used = data.get("tools_used", [])
        s.time_remaining = data.get("time_remaining", 300)
        s.difficulty_level = DifficultyLevel(data.get("difficulty_level", "easy"))
        s.current_reward = data.get("current_reward", 0.0)
        s.done = data.get("done", False)
        s.last_message = data.get("last_message", "")
        s.generated_content = data.get("generated_content", {})
        return s


# ---------------------------------------------------------------------------
# Action
# ---------------------------------------------------------------------------

@dataclass
class CampusAction:
    """
    A typed action the agent sends to step().

    action_type : one of ActionType
    parameters  : optional keyword arguments forwarded to the action handler
    """

    action_type: ActionType
    parameters: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {"action_type": self.action_type.value, "parameters": self.parameters}

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "CampusAction":
        return cls(
            action_type=ActionType(data["action_type"]),
            parameters=data.get("parameters", {}),
        )

    @classmethod
    def from_string(cls, action_str: str) -> "CampusAction":
        """Convenience: create action from a raw string like 'search_notes'."""
        return cls(action_type=ActionType(action_str))


# ---------------------------------------------------------------------------
# Task Definition
# ---------------------------------------------------------------------------

@dataclass
class TaskDefinition:
    """
    Full specification of one campus task.

    task_id          : unique identifier
    name             : display name
    user_goal        : the goal string shown to the agent
    difficulty       : easy / medium / hard
    required_steps   : ordered list of ActionType values that must be completed
    optional_steps   : additional steps that earn bonus reward
    time_limit       : max seconds per episode
    reward_weights   : dict mapping reward component names → float (must sum ≤ 1.0)
    description      : human-readable longer description
    """

    task_id: str
    name: str
    user_goal: str
    difficulty: DifficultyLevel
    required_steps: List[ActionType]
    optional_steps: List[ActionType] = field(default_factory=list)
    time_limit: int = 300
    reward_weights: Dict[str, float] = field(default_factory=dict)
    description: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "name": self.name,
            "user_goal": self.user_goal,
            "difficulty": self.difficulty.value,
            "required_steps": [s.value for s in self.required_steps],
            "optional_steps": [s.value for s in self.optional_steps],
            "time_limit": self.time_limit,
            "reward_weights": self.reward_weights,
            "description": self.description,
        }


# ---------------------------------------------------------------------------
# Step Result
# ---------------------------------------------------------------------------

@dataclass
class StepResult:
    """
    The tuple returned by env.step(action).

    observation : updated CampusState
    reward      : incremental reward earned this step (0.0 – 1.0)
    done        : True if the episode has ended
    info        : auxiliary diagnostic information
    """

    observation: CampusState
    reward: float
    done: bool
    info: Dict[str, Any] = field(default_factory=dict)

    def to_tuple(self):
        """Unpack as (obs, reward, done, info) — standard OpenEnv convention."""
        return self.observation, self.reward, self.done, self.info
